### ISSUE TITLE
Protostuff-maven-plugin: protoModule without output definition gives NPE

### ISSUE THREAD

**Issue by xpromache** [protostuff/protostuff#117]
I noticed that you get a NullPointerException if defining in pom.xml a protoModule without an <output>.
It would be nicer if it gave a more informative message...
The stack trace:

```
Caused by: java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at java.util.regex.Pattern.split(Pattern.java:1206)
        at java.util.regex.Pattern.split(Pattern.java:1273)
        at io.protostuff.mojo.ProtoCompilerMojo.updateRelativeOutputLocation(ProtoCompilerMojo.java:224)
        at io.protostuff.mojo.ProtoCompilerMojo.execute(ProtoCompilerMojo.java:158)
 ... 21 more
```

**Comment by kshchepanovskyi** [comment]
Thank you for reporting this issue. Will gladly accept PRs.

**Comment by kshchepanovskyi** [comment]
fixed
