### ISSUE TITLE
Serialization of null in Enumeration ArrayList

### ISSUE THREAD

**Issue by bojanv55** [protostuff/protostuff#174]
There is a problem with serialization when null value is inside ArrayList consisting of Enumerations.

````
Exception in thread "main" java.lang.NullPointerException
	at io.protostuff.runtime.EnumIO.getTag(EnumIO.java:252)
	at io.protostuff.runtime.EnumIO.writeTo(EnumIO.java:133)
	at io.protostuff.runtime.RuntimeRepeatedFieldFactory$2.writeTo(RuntimeRepeatedFieldFactory.java:177)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:457)
	at io.protostuff.GraphIOUtil.toByteArray(GraphIOUtil.java:261)
```

**Comment by kshchepanovskyi** [comment]
Looks like a bug. Will gladly accept a pull request :)

**Comment by kshchepanovskyi** [comment]
Fixed in https://github.com/protostuff/protostuff/releases/tag/protostuff-1.4.3
