### ISSUE TITLE
use GraphIOUtil.mergeFrom and GraphIOUtil.writeTo throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by muyuqiu001** [protostuff/protostuff#181]
here is my test code:

client code:
````java
class ClassB
{
    @Tag(1)
    private String b1;

    ClassB()
    {
        this.b1 = "b1";
    }
}

class SuperClassA
{
    @Tag(1)
    private String sa1;
}

class ClassA extends SuperClassA
{
    @Tag(101)
    private String a1;

    @Tag(102)
    private ClassB a2;

    public ClassA(ClassB a2)
    {
    }
}
````

server code:
````java
class ClassB
{
    @Tag(1)
    private String b1;

    ClassB()
    {
        this.b1 = "b1";
    }
}
class SuperClassA
{
    @Tag(1)
    private String sa1;

    @Tag(2)
    private ClassB sa2;

    public SuperClassA(ClassB sa2)
    {
        this.sa1 = "sa1";
        this.sa2 = sa2;
    }
}

class ClassA extends SuperClassA
{
    @Tag(101)
    private String a1;

    @Tag(102)
    private ClassB a2;

    public ClassA(ClassB a2)
    {
        super(a2);
        this.a1 = "a1";
        this.a2 = a2;
    }
}
````
Protostuff Version:1.0.7
I use the GraphIOUtil.writeTo on server site to serialize the object, and then on client site use client code to deserialize the object. Then it will throws IndexOutOfBoundsException.

but if i use ProtostuffUtil to serialize and deserialize the object, it will pass successfully.
I want to know whether is this a bug of the GraphUtil, and if this is a bug, which version have been resolved ? 
here is the exception stack:
````xml
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at com.dyuproject.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:98)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$14$1.mergeFrom(RuntimeUnsafeFieldFactory.java:828)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:188)
	at com.dyuproject.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:627)
	at com.dyuproject.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:312)
	at com.dyuproject.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:153)
	at com.dyuproject.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:271)
	at com.dyuproject.protostuff.CodedInput.mergeObject(CodedInput.java:239)
	at com.dyuproject.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:108)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.mergeFrom(RuntimeUnsafeFieldFactory.java:904)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:188)
	at com.dyuproject.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:91)
````

thanks

**Comment by muyuqiu001** [comment]
In my opinion, the <code>Tag</code> provides the incompatible ability of server code and client code.
but I use the <code>Tag</code>, it is not useful

**Comment by dyu** [comment]
Please provide the complete test code.
It looks like your message instance has fields pointing to it.
See http://www.protostuff.io/documentation/object-graphs/

**Comment by muyuqiu001** [comment]
@dyu 
here is the test main class and not using client ClassA to deserialize server ClassA:
they are different with each other is that in super classA
![image](https://cloud.githubusercontent.com/assets/971514/15418956/815ffe48-1e95-11e6-823c-364bef906cc7.png)


````java
package com.test.yyy;

import java.io.ByteArrayInputStream;
import java.io.IOException;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.LinkedBuffer;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.runtime.RuntimeSchema;

public class TestMain
{
    public static void main(String[] args) throws IOException
    {
        ClassB b = new ClassB();
        ClassA a = new ClassA(b);
        // serializeGraph(a);
        // follow byte is that serialized server ClassA byte code
        byte[] tmpbyte = {10, 3, 115, 97, 49, 19, 10, 2, 98, 49, 20, -86, 6, 2, 97, 49, -74, 6, 0};
        deserializeGraph(tmpbyte, ClassA.class);
    }

    private static <T> byte[] serializeGraph(T object)
    {
        @SuppressWarnings("unchecked")
        Class<T> clazz = (Class<T>) object.getClass();
        Schema<T> schema = RuntimeSchema.getSchema(clazz);
        LinkedBuffer buffer = LinkedBuffer.allocate(2048);
        byte[] result = GraphIOUtil.toByteArray(object, schema, buffer);
        buffer.clear();
        return result;
    }

    private static <T> T deserializeGraph(byte[] bytes, Class<T> clz) throws IOException
    {
        Schema<T> schema = RuntimeSchema.getSchema(clz);
        T obj = schema.newMessage();
        ByteArrayInputStream bis = new ByteArrayInputStream(bytes);
        GraphIOUtil.mergeFrom(bis, obj, schema);
        return obj;
    }
}
````

and then it throws 
````xml
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at com.dyuproject.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:98)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.mergeFrom(RuntimeUnsafeFieldFactory.java:773)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:188)
	at com.dyuproject.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:76)
	at com.test.yyy.TestMain.deserializeGraph(TestMain.java:67)
	at com.test.yyy.TestMain.main(TestMain.java:48)
````

**Comment by dyu** [comment]
I was able to reproduce.
What's happening is that on the server's serialization, this points to a reference (tag 2)
```java
    @Tag(102)
    private ClassB a2;
```

When you receive the data in the client, the tag 102 is present but what it is pointing to, is absent.
You've to make sure that the fields you exclude have higher numbers.
This means that the excluded fields will always be the references (the ones pointing to the actual pojo).

E.g 
```java
class SuperClassA
{
    @Tag(201)
    private String sa1;

    @Tag(202)
    private ClassB sa2;

    public SuperClassA(ClassB sa2)
    {
        this.sa1 = "sa1";
        this.sa2 = sa2;
    }
}
```

A fix to handle this case can be seen in https://github.com/protostuff/protostuff/pull/182

**Comment by dyu** [comment]
--> https://github.com/protostuff/protostuff/pull/183

**Comment by muyuqiu001** [comment]
@dyu if i using different tag 
````java
class SuperClassA
{
    @Tag(201)
    private String sa1;

    @Tag(202)
    private ClassB sa2;

    public SuperClassA(ClassB sa2)
    {
        this.sa1 = "sa1";
        this.sa2 = sa2;
    }
}
````

it throws the protostuffexception
````xml
Exception in thread "main" com.dyuproject.protostuff.ProtobufException: Protocol message tag had invalid wire type.
	at com.dyuproject.protostuff.ProtobufException.invalidWireType(ProtobufException.java:108)
	at com.dyuproject.protostuff.CodedInput.skipField(CodedInput.java:163)
	at com.dyuproject.protostuff.CodedInput.handleUnknownField(CodedInput.java:985)
	at com.dyuproject.protostuff.FilterInput.handleUnknownField(FilterInput.java:38)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:186)
	at com.dyuproject.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:76)
	at com.huawei.csc.compress.TestMain.deserializeGraph(TestMain.java:41)
	at com.huawei.csc.compress.TestMain.main(TestMain.java:22)
````

**Comment by dyu** [comment]
Yes.  Protostuff 1.0.9 needs to be patched with https://github.com/protostuff/protostuff/pull/183/commits/7dee3a4dab0baa543e1eec87419a2e064ffdc0a0

**Comment by muyuqiu001** [comment]
OK, thanks

**Comment by dyu** [comment]
I'll try to do a 1.0.10 release this weekend.

**Comment by kshchepanovskyi** [comment]
@dyu you can make a branch with name `protostuff-1.0.x`, and I have a jenkins job for releases - making a release is as simple as possible - just click a button :)

**Comment by dyu** [comment]
Yeah that's a good idea.
I was experimenting with https://github.com/mjiderhamn/promote-maven-plugin but it didn't deliver.

**Comment by kshchepanovskyi** [comment]
That plugin looks like some hackish tool for projects that take hours to compile:) Not our case.

Here is how I run release in my Jenkins instance:

![image](https://cloud.githubusercontent.com/assets/4040120/15440326/94d9d500-1edd-11e6-9d5c-6aa695d8b3a5.png)

Set few parameters (usually they are filled automatically) and press a button, done.
Later I will add an option to use multiple branches.

**Comment by dyu** [comment]
Cool.  Good thing there is jenkins that takes away the maven's release pain.
I was looking for a script that just basically syncs my local repository to nexus's repository with the target jars and gpgs signatures.

**Comment by kshchepanovskyi** [comment]
You cannot sync your local repo to maven central, this is not "maven" way (release process is well standartized) :) 
Jenkins/any other CI + maven release plugin is more standard and preferrable for this.

**Comment by dyu** [comment]
@muyuqiu001 A snapshot has been released (1.0.10-SNAPSHOT).
I've having troubles releasing at the moment.  Once @kshchepanovskyi 's jenkins has multiple branch support is available, it will soon follow.

**Comment by dyu** [comment]
@muyuqiu001 1.0.10 is now in central.

**Comment by kshchepanovskyi** [comment]
@dyu Can you please push source code for `1.0.x` branch to this repository? As far as I understand it is not on the Google Code anymore.

**Comment by kshchepanovskyi** [comment]
@dyu done:

![image](https://cloud.githubusercontent.com/assets/4040120/15448214/1198d6fa-1f64-11e6-8177-e607085f03f6.png)

I will send additional information how to access this job usin email.

**Comment by muyuqiu001** [comment]
@dyu 

I don't know if i should creat a new issue.

according to RuntimeGraphUnknownFieldTest.java, if i change client code like this:
````java
    static final class Client
    {
        static class ClassB
        {
            @Tag(1)
            String b1;

            ClassB()
            {
                this.b1 = "b1";
            }
        }

        static class SuperClassA
        {
            @Tag(201)
            String sa1;

            // be the same with server
            @Tag(202)
            ClassB sa2;
        }

        static class ClassA extends SuperClassA
        {
            @Tag(101)
            String a1;

            // @Tag(102)
            // ClassB a2;

            public ClassA(ClassB a2)
            {

            }
        }
    }
````
then run the test, it will throw java.lang.IndexOutOfBoundsException
````xml
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at com.dyuproject.protostuff.GraphByteArrayInput.mergeObject(GraphByteArrayInput.java:98)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.mergeFrom(RuntimeUnsafeFieldFactory.java:787)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:196)
	at com.dyuproject.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:52)
	at com.dyuproject.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:39)
	at io.protostuff.runtime.RuntimeGraphUnknownFieldTest.deserializeGraph(RuntimeGraphUnknownFieldTest.java:144)
	at io.protostuff.runtime.RuntimeGraphUnknownFieldTest.main(RuntimeGraphUnknownFieldTest.java:125)
````

I changed the code run test to main method.

**Comment by dyu** [comment]
Its straightforward to understand.
After server serialization, 202 points to 102 (which doesn't exist in the client).
As I said earlier:
```
You've to make sure that the fields you exclude have higher numbers (e.g will be serialized last).
```

When you design your classes, document which ones will be excluded.
**Construct** them appropriately that the excluded fields will always be serialized last.
You can send me an email with your dataset and I'll try to give you some pointers how to go about it.

**Comment by dyu** [comment]
Another way to solve this is to simply return null on deser if what it's pointing to, does not exist.
That would not be the correct solution since that field would be present if you accidentally construct your objects a little bit differently.  What you want to achieve is consistent behavior.

**Comment by muyuqiu001** [comment]
@dyu 
We can't ensure the excluded fields will always be serialized last in class and its derived class.
Yes, to simply return null on deser if what it's pointing to, does not exist, this would not be the correct solution.
The tag which does not exist may pointing to a known type value, which could be found by other reference tag.
So we should try to deser a object by its all reference tag, and if all reference tag do not exist, simply return null.
