### ISSUE TITLE
No enum constant io.protostuff.MapSchema.MessageFactories.Properties

### ISSUE THREAD

**Issue by gaigeshen** [protostuff/protostuff#221]
java.lang.IllegalArgumentException: No enum constant io.protostuff.MapSchema.MessageFactories.Properties
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.protostuff.MapSchema$MessageFactories.valueOf(MapSchema.java:53)
	at io.protostuff.runtime.DefaultIdStrategy.getMapFactory(DefaultIdStrategy.java:288)
	at io.protostuff.runtime.RuntimeMapFieldFactory$17.create(RuntimeMapFieldFactory.java:1866)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:275)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:187)
	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:116)
	at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:709)
	at io.protostuff.runtime.RuntimeMessageField.getSchema(RuntimeMessageField.java:51)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeRepeatedFieldFactory$3.writeTo(RuntimeRepeatedFieldFactory.java:174)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:1016)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffIOUtil.toByteArray(ProtostuffIOUtil.java:186)

**Comment by gaigeshen** [comment]
Here is my class,
`public final class KafkaData implements Serializable {
  
  private static final long serialVersionUID = 1L;
  
  private long id;
  private Object data;
  
  private KafkaData() { }
  
  public KafkaData(long id, Object data) {
    
    this();
    
    this.id = id;
    this.data = data;
  }

  public long getId() {
    return id;
  }

  public Object getData() {
    return data;
  }

  
}`

**Comment by kshchepanovskyi** [comment]
I have few ideas why it might happen, but in order to fix this faster - can you please write a unit test that reproduces the problem?

**Comment by kshchepanovskyi** [comment]
It seems that `io.protostuff.MapSchema.MessageFactories` should contain an entry for `java.util.Properties`.

**Comment by gaigeshen** [comment]
The data field of KafkaData object is another object, that object is complex, I changed that object, keep it simple, finally, No error occurred.

That object extends this class:
```
public abstract class BaseModel implements Model<Long> {
  
  private Long id = -1L;
  
  @JsonIgnore
  // All properties mapping but id
  private List<ResultMappingValue> mappingValues = new ArrayList<>();
  
  public BaseModel() {
    
    List<ResultMapping> mappings = ResultMappings.getMappings(getClass());
    
      for (ResultMapping mapping : mappings) {
        
        if (!mapping.getProperty().equals("id")) {
          this.mappingValues.add(new ResultMappingValue(mapping));
        }
      }
  }
  
  @JsonIgnore
  public List<ResultMappingValue> getValues() {

    try {
      for (ResultMappingValue mapping : mappingValues) {

        ResultMapping rm = mapping.getMapping();

        String property = rm.getProperty();

        Field field = FieldUtils.getField(getClass(), property, true);

        mapping.value(field.get(this));
      }

      return Collections.unmodifiableList(mappingValues);

    } catch (IllegalAccessException e) {
      throw new IllegalStateException(
          "Cannot get field value of type " + getClass().getName());
    }

  }
  
  @Override
  public Long getId() {
    return this.id;
  }
  
  @Override
  public void setId(Long id) {
    this.id = id;
  }
  
  @Override
  public int hashCode() {
    return this.id.hashCode();
  }

  @Override
  public boolean equals(Object obj) {
    
    if (this == obj)
      return true;
    
    if (obj == null || this.getClass() != obj.getClass())
      return false;
    
    BaseModel that = (BaseModel) obj;
    
    return this.id.equals(that.id);
  }
  
  /**
   * 
   * @author gaigeshen
   * @since 04/26 2017
   */
  class ResultMappingValue {
    
    private ResultMapping mapping;
    private Object value;
    
    public ResultMappingValue(ResultMapping mapping) {
      this.mapping = mapping;
    }
    
    public String property() {
      return mapping.getProperty();
    }
    
    public String column() {
      return mapping.getColumn();
    }

    public Object getValue() {
      return value;
    }

    public void value(Object value) {
      this.value = value;
    }

    public ResultMapping getMapping() {
      return mapping;
    }
    
  }

}
```

**Comment by gaigeshen** [comment]
No  `java.util.Properties` in `io.protostuff.MapSchema.MessageFactories`

**Comment by kshchepanovskyi** [comment]
Fixed in version `1.5.5`

**Comment by kshchepanovskyi** [comment]
@gaigeshen please check if problem is resolved.

**Comment by gaigeshen** [comment]
Resolved, thanks
