### ISSUE TITLE
Exception for serializing off heap buffer

### ISSUE THREAD

**Issue by xingbowu** [protostuff/protostuff#225]
StackOverflow Exception for serializing off heap ByteBuffer by allocateDirect()

Demo as below:

      public static void main(String[] args) {
          ByteBuffer buf= ByteBuffer.allocateDirect(100);
          for(int i=1; i<=buf.capacity()/4; i++) {
              buf.putInt(i);
          }
          byte[] protostuffByte ;
          LinkedBuffer buffer = LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE);
          Class<ByteBuffer> clazz = (Class<ByteBuffer>) buf.getClass();
          try {
              Schema<ByteBuffer> schema = RuntimeSchema.getSchema(clazz);
              protostuffByte = ProtostuffIOUtil.toByteArray(buf, schema, buffer);
          } catch (Exception e) {
              throw new IllegalStateException(e.getMessage(), e);
          } finally {
              buffer.clear();
          }
      }

> Exception in thread "main" java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at io.protostuff.runtime.DefaultIdStrategy.tryWriteDelegateIdTo(DefaultIdStrategy.java:432)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:718)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:1048)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363)

**Comment by dyu** [comment]
1.  Use a pojo that wraps the buffer.
2.  Register a [delegate](http://www.protostuff.io/documentation/runtime-schema-delegate/) for the byte buffer.
