### ISSUE TITLE
Runtime Schema Serialization of a large object graph - Overflow

### ISSUE THREAD

**Issue by sternr** [protostuff/protostuff#226]
Hey,

When trying to serialize a large object graph using Runtime Schema, we're sometimes getting:

```
Java.lang.StackOverflowError
	at io.protostuff.StreamedStringSerializer.writeUTF8VarDelimited(StreamedStringSerializer.java:465) ~[protostuff-api-1.5.3.jar:1.5.3]
	at io.protostuff.StreamedStringSerializer.writeUTF8VarDelimited(StreamedStringSerializer.java:566) ~[protostuff-api-1.5.3.jar:1.5.3]
	at io.protostuff.WriteSink$2.writeStrUTF8VarDelimited(WriteSink.java:591) ~[protostuff-api-1.5.3.jar:1.5.3]
	at io.protostuff.ProtostuffOutput.writeString(ProtostuffOutput.java:299) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.DefaultIdStrategy.tryWritePojoIdTo(DefaultIdStrategy.java:484) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:750) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232) ~[protostuff-runtime-1.5.3.jar:1.5.3]
```

**Comment by dyu** [comment]
If your data has cyclic references, use GraphIOUtil

**Comment by sternr** [comment]
There's no cyclic references, just a very deep object graph.

**Comment by dyu** [comment]
Can you post the full stack trace?

**Comment by sternr** [comment]
This continues for a couple of thousand of lines and ends at:
```
        at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232) ~[protostuff-runtime-1.5.3.jar:1.5.3]
        at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475) ~[protostuff-runtime-1.5.3.jar:1.5.3]
        at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:761) ~[protostuff-runtime-1.5.3.jar:1.5.3]
        at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356) ~[protostuff-runtime-1.5.3.jar:1.5.3]
        at io.protostuff.ProtostuffOutput.writeObject(ProtostuffOutput.java:363) ~[protostuff-core-1.5.3.jar:1.5.3]
        at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232) ~[protostuff-runtime-1.5.3.jar:1.5.3]
        at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475) ~[protostuff-runtime-1.5.3.jar:1.5.3]
```

**Comment by dyu** [comment]
The full stacktrace would help identify the culprit.  Just redact some "confidential" details (or send it privately)

**Comment by sternr** [comment]
I don't have more than that, as I said looking in the log All I see is the above lines recursively called over 1000 times.
If it help, here's a strapped out version of the calling code:

```
LinkedBuffer protoBuffer = LinkedBuffer.allocate(protoBufferSize);
Schema<E> schema = RuntimeSchema.getSchema((Class<E>) state.getClass());
FileOutputStream outputStream = new FileOutputStream(new File(filePath));
int size = io.protostuff.ProtostuffIOUtil.writeTo(outputStream, state, schema, protoBuffer);
outputStream.close();

```

**Comment by dyu** [comment]
You're basically trying to serialize a class which internally has circular references.

**Comment by sternr** [comment]
No, I logged every object data upon crash and verified there are no cyclic reference.
However, I'll give some more information about the object's deep structure: 
Its a pojo that has very little internal fields, and a very large ArrayList of complex object that have a simple linked-list like implementation inside one of the child objects that could get as long as 200 items.

**Comment by kshchepanovskyi** [comment]
Can you please write some unit test that will show a problem?

**Comment by sternr** [comment]
Also, when trying to run the same flow with GraphIOUtil, we get:


```
java.lang.StackOverflowError
	at io.protostuff.StringSerializer$STRING.deser(StringSerializer.java:1148) ~[protostuff-api-1.5.3.jar:1.5.3]
	at io.protostuff.CodedInput.readString(CodedInput.java:283) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.FilterInput.readString(FilterInput.java:135) ~[protostuff-api-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.DefaultIdStrategy.resolvePojoFrom(DefaultIdStrategy.java:522) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:682) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:350) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:171) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:336) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.CodedInput.mergeObject(CodedInput.java:298) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:111) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.mergeFrom(RuntimeUnsafeFieldFactory.java:1217) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:693) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:350) ~[protostuff-runtime-1.5.3.jar:1.5.3]
	at io.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:171) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:336) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.CodedInput.mergeObject(CodedInput.java:298) ~[protostuff-core-1.5.3.jar:1.5.3]
	at io.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:111) ~[protostuff-core-1.5.3.jar:1.5.3]


```

**Comment by dyu** [comment]
See http://www.protostuff.io/documentation/object-graphs/
A root cannot have its members reference it.  Use a wrapper.
And like @kshchepanovskyi  said, a test-case to reproduce would be good.

**Comment by sternr** [comment]
I have,
My class hierarchy is as follows:

```
class GenericWrapper<T>
{ public T data; }

class RealItem{
/* about a dozen primitive fields, including a few int[] and long[] */
private ChildItem firstChild;
}

class ChildItem{
/* a few primitive fields */
private ChildItem nextItem;
}

```
And the object i'm trying to serialize is basically a GenericWrapper<ArrayList<RealItem>> containing roughly a few thousands of RealItems, where the firstChild "linked-list" could get long as 300 items

**Comment by sternr** [comment]
Just to add, serialization usually works, its deserialization that fails

**Comment by squallud** [comment]
hello all, Is there any updated of this issue?
We are executing some benchmark tests of protostuff,  and we encountered the same StackOverflowError when we executed serialize/deserialize more than 700+ times.

**Comment by dyu** [comment]
Can you attach a testcase? A testcase that we could replicate this issue would help identify and fix the problems

**Comment by ZenLiuCN** [comment]
just i my case, there is a java.nio.file.Path will cause StackOverflow.
