### ISSUE TITLE
stackoverflow occurs when set LinkedHashMap#Entry in List

### ISSUE THREAD

**Issue by beanww** [protostuff/protostuff#230]
below code can reproduce  this issue, both linkedHashMap and TreeMap's Entry have the some error:
public static void main(String[] args)
        throws Throwable
    {
        Wrapper wrapper = new Wrapper();
        Map<String, Object> linkmap = new LinkedHashMap<String, Object>();
        linkmap.put("k1", "v1");
        ArrayList list = new ArrayList();
        Iterator it = linkmap.entrySet().iterator();
        list.add(it.next());
        wrapper.setObject(list);
        
        Schema<Wrapper> schema = RuntimeSchema.getSchema(Wrapper.class);
        LinkedBuffer buffer = LinkedBuffer.allocate(256);
        byte[] data = GraphIOUtil.toByteArray(wrapper, schema, buffer);
        
        Wrapper newwrapper = new Wrapper();
        GraphIOUtil.mergeFrom(data, newwrapper, schema);
}
}
class Wrapper
{
    private Object object;
    
    public Wrapper()
    {
    }
    
    public void setObject(Object obj)
    {
        this.object = obj;
    }
    
    public Object getObject()
    {
        return this.object;
    }
}

exception stack:
Exception in thread "main" java.lang.StackOverflowError
	at com.dyuproject.protostuff.GraphProtostuffOutput$IdentityMap.hash(GraphProtostuffOutput.java:200)
	at com.dyuproject.protostuff.GraphProtostuffOutput$IdentityMap.shouldIncrement(GraphProtostuffOutput.java:298)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:55)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)
	at com.dyuproject.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.writeTo(RuntimeUnsafeFieldFactory.java:779)
	at com.dyuproject.protostuff.runtime.MappedSchema.writeTo(MappedSchema.java:195)

.....
the same....

**Comment by Mr14huashao** [comment]
Copy your test cases and pass, and maybe update should solve the problem.
