### ISSUE TITLE
Exception when serializing "Byte[]" array

### ISSUE THREAD

**Issue by Medyk** [protostuff/protostuff#232]
Exception while serializing class having "Byte[]" array.

Test program (fails on ProtostuffIOUtil.toByteArray()):
```
package pl.medima.test;

import io.protostuff.LinkedBuffer;
import io.protostuff.ProtostuffIOUtil;
import io.protostuff.Schema;
import io.protostuff.runtime.RuntimeSchema;

public class ProtostuffTest
{
    public static void main(final String[] args) throws Exception
    {
        BadClass message = new BadClass();
        message.badArray = new Byte[5];
        Schema<BadClass> schema = RuntimeSchema.getSchema(BadClass.class);
        LinkedBuffer buffer = LinkedBuffer.allocate(10000);
        byte[] bytes = ProtostuffIOUtil.toByteArray(message, schema, buffer);

        BadClass result = new BadClass();
        ProtostuffIOUtil.mergeFrom(bytes, result, schema);

        System.out.println("Done");
    }
    
    public static class BadClass
    {
        public Byte[] badArray;
    }
}
```

Exception:
```
Exception in thread "main" java.lang.RuntimeException: Should not happen.
	at io.protostuff.runtime.ArraySchemas.newSchema(ArraySchemas.java:204)
	at io.protostuff.runtime.PolymorphicSchemaFactories$1.newSchema(PolymorphicSchemaFactories.java:67)
	at io.protostuff.runtime.RuntimeObjectField.<init>(RuntimeObjectField.java:41)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.<init>(RuntimeUnsafeFieldFactory.java:1212)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15.create(RuntimeUnsafeFieldFactory.java:1210)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:275)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:187)
	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:116)
	at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:709)
	at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:149)
	at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:140)
	at pl.medima.test.ProtostuffTest.main(ProtostuffTest.java:14)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
Java Result: 1
```

**Comment by Mr14huashao** [comment]
Byte[]  is a wrapper class.
Please :
public Byte[] badArray;   ---------->   public byte[] badArray;
protostuff  dose ont process the wrapper class.

**Comment by Medyk** [comment]
It seems that protostuff supports other wrapper classes but not Byte.
https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ArraySchemas.java#L111

**Comment by Mr14huashao** [comment]
@Medyk I've been trying to modify some of code, replacing byte [] to Byte [].
But is the amendment necessary ?
