### ISSUE TITLE
RuntimeSchema.getSchema(Long.class) will case EXCEPTION

### ISSUE THREAD

**Issue by zhenian** [protostuff/protostuff#235]
```
java.lang.RuntimeException: Could not resolve constructor for class java.lang.Long
	at io.protostuff.runtime.RuntimeEnv.newInstantiator(RuntimeEnv.java:320)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:282)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:187)
	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:116)
	at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:709)
	at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:149)
	at io.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:140)
```

```
    private ThreadLocal<LinkedBuffer> ThreadLocalBuffer = new ThreadLocal<LinkedBuffer>() {
        @Override
        protected LinkedBuffer initialValue() {
            return LinkedBuffer.allocate(1024);
        }
    };

    public <C> byte[] encodeList(List<C> list, Class<C> elementClass) {
        if (list == null || list.size() == 0) {
            throw new NullPointerException("Can't serialize null list");
        }
        long t = System.currentTimeMillis();
        LinkedBuffer buffer = ThreadLocalBuffer.get();
        byte bytes[] = null;
        try {
            Long i = 1L;
            Schema<C> schema = RuntimeSchema.getSchema(elementClass);
            MessageCollectionSchema<C> collSchema = new MessageCollectionSchema<C>(schema);
            bytes = ProtostuffIOUtil.toByteArray(list, collSchema, buffer);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            buffer.clear();
        }
        logger.debug("encodeList use time :" + (System.currentTimeMillis() - t));
        return bytes;
    }
```

**Comment by zhenian** [comment]
```
/**
 * A schema that can be generated and cached at runtime for objects that have no schema. This is particularly useful for
 * pojos from 3rd party libraries.
 * 
 * @author David Yu
 */
public final class RuntimeSchema<T> implements Schema<T>, FieldMap<T>
{

```

RuntimeSchema is for pojos
