### ISSUE TITLE
ClassLoader.loadClass(java.lang.String) on a null object reference

### ISSUE THREAD

**Issue by mikelhm** [protostuff/protostuff#272]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
        at io.protostuff.runtime.RuntimeEnv.loadClass(RuntimeEnv.java:297)
        at io.protostuff.runtime.DefaultIdStrategy.getSchemaWrapper(DefaultIdStrategy.java:185)
        at io.protostuff.runtime.DefaultIdStrategy.resolvePojoFrom(DefaultIdStrategy.java:524)
        at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:682)
        at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:350)
        at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:488)
        at io.protostuff.runtime.RuntimeRepeatedFieldFactory$5.mergeFrom(RuntimeRepeatedFieldFactory.java:268)
        at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466)
        at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:693)
        at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:350)
        at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:488)
        at io.protostuff.runtime.RuntimeReflectionFieldFactory$15$1.mergeFrom(RuntimeReflectionFieldFactory.java:1399)

**Comment by mikelhm** [comment]
version 1.5.2

**Comment by dyu** [comment]
It looks like ```Thread.currentThread().getContextClassLoader()``` returned null based on your stacktrace.

**Comment by dyu** [comment]
What jvm version are you using?

**Comment by mikelhm** [comment]
> It looks like `Thread.currentThread().getContextClassLoader()` returned null based on your stacktrace.

YES  How to solve the problem, Do you have any idea?
![image](https://user-images.githubusercontent.com/10327642/67454085-8415f880-f65b-11e9-8470-ea83a39ed9fc.png)

**Comment by dyu** [comment]
Try a newer version of java 1.8
That release you have may have had a regression (bug)
