### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ahcjz** [protostuff/protostuff#275]
deserialize throw Exception when object field is EmptyMap. Example: 
```
public class Test {
     private Map map;
     public Test() {
           map = Collections.emptyMap();
     }
}
```
Exception like this:
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at io.protostuff.MapSchema$MapWrapper.put(MapSchema.java:604)
	at io.protostuff.runtime.RuntimeMapFieldFactory$16.vPutFrom(RuntimeMapFieldFactory.java:1854)
	at io.protostuff.runtime.RuntimeMapField$1.putValueFrom(RuntimeMapField.java:61)
	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:493)
	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:388)
	at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:518)
	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:490)
	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:334)
	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:31)
	at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:518)
	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:490)
	at io.protostuff.runtime.RuntimeMapFieldFactory$16.mergeFrom(RuntimeMapFieldFactory.java:1771)

**Comment by dyu** [comment]
Your constructor is being called by protostuff and the map instance you provided is being used during deserialization.
Try setting: ```-Dprotostuff.runtime.always_use_sun_reflection_factory=true```

**Comment by ahcjz** [comment]
> Your constructor is being called by protostuff and the map instance you provided is being used during deserialization.
> Try setting: `-Dprotostuff.runtime.always_use_sun_reflection_factory=true`

think you
