### ISSUE TITLE
ProtostuffException is hidden by RuntimeException

### ISSUE THREAD

**Issue by mirlord** [protostuff/protostuff#291]
**Protostuff runtime version:** 1.6.2 (but the same problem applies to master, though the stack trace may differ a bit).

**Problem summary:** the root cause of the problem was schema incompatibility - write and read operations were out of sync, that caused protostuff to fail with the following stack trace (which is fairly fine, but could be handled better, see details below):
```
Caused by: java.lang.RuntimeException: io.protostuff.ProtostuffException: The map was incorrectly serialized.
at io.protostuff.runtime.RuntimeMapFieldFactory$4.mergeFrom(RuntimeMapFieldFactory.java:397)
at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466)
at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:694)
at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:351)
at io.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:171)
at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:359)
at io.protostuff.CodedInput.mergeObject(CodedInput.java:321)
at io.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:111)
at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.mergeFrom(RuntimeUnsafeFieldFactory.java:1229)
at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466)
at io.protostuff.GraphIOUtil.mergeFrom(GraphIOUtil.java:76)
[... hidden ...]
... 62 more
Caused by: io.protostuff.ProtostuffException: The map was incorrectly serialized.
at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:522)
at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:414)
at io.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:171)
at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:359)
at io.protostuff.CodedInput.mergeObject(CodedInput.java:321)
at io.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:111)
at io.protostuff.MapSchema.mergeFrom(MapSchema.java:360)
at io.protostuff.MapSchema.mergeFrom(MapSchema.java:33)
at io.protostuff.GraphCodedInput.mergeFrom(GraphCodedInput.java:171)
at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:359)
at io.protostuff.CodedInput.mergeObject(CodedInput.java:321)
at io.protostuff.GraphCodedInput.mergeObject(GraphCodedInput.java:111)
at io.protostuff.runtime.RuntimeMapFieldFactory$4.mergeFrom(RuntimeMapFieldFactory.java:392)
... 85 more
```

The caller of `GraphIOUtils` expects it to fail with `ProtobufException` or `ProtostuffException` or `IOException`, and that's usually the case. That allows a caller to identify data-related issue and handle it accordingly. In this particular case `RuntimeMapFieldFactory` intercepts the `ProtostuffException` thrown by `MapSchema` and wraps it with a `RuntimeException`. This behavior was introduced by the following commit and should be considered as a regression:
```
commit b5d7bc3d88a45450fab12b79bcb342e84b7bbb08
Author: Konstantin Shchepanovskyi <schepanovsky@gmail.com>
Date:   Thu Sep 8 23:23:13 2016 +0300

    Restore Java 6 compatibility
```

Where this:
```
catch (IllegalArgumentException | IllegalAccessException e)
{
    throw new RuntimeException(e);
}
```

was replaced by:
```
catch (Exception e)
{
    throw new RuntimeException(e);
}
```

**Proposed solution:**
1. Revert the aforementioned commit, because nowadays the source level compatibility is 1.7 anyways. That will fix the same problem in 260 different places at once.
2. Also, we might consider throwing a checked `ProtostuffException` here instead of a generic unchecked `RuntimeException`. At least all the methods of `RuntimeMapFieldFactory` already has `throws IOException` in method declarations anyways, didn't check other classes yet. Would it be a good thing to do? Not sure, because there could be reasons not to do that in the first place. Please advise.

Let's come up with some plan here, then I'll be happy to take care of opening a PR with a proper fix.

**Comment by mirlord** [comment]
Here's a revert commit I've prepared:
https://github.com/mirlord/protostuff/commit/6124fb987d1896ce4496c415c189ff290bea3561

**Comment by dyu** [comment]
The multiple catch statement is the preferrable fix ... not having to change source level.
```java
catch (IllegalArgumentException) { throw new RuntimeException(e); }
catch (InvocationTargetException) { throw new RuntimeException(e); }
catch (IllegalAccessException) { throw new RuntimeException(e); }
```
