### ISSUE TITLE
VerifyError: class io.protostuff.JsonIOUtil$Factory overrides final method 

### ISSUE THREAD

**Issue by rymarm** [protostuff/protostuff#315]
Here is ERROR log:
```
java.lang.VerifyError: JVMVRFY007 final method overridden; class=io/protostuff/JsonIOUtil$Factory, method=getGeneratorFeatures()I, pc=0
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:396)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:357)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:951)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:896)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879)
	at io.protostuff.JsonIOUtil.<clinit>(JsonIOUtil.java:84)
```

This error reproduces for `protostuff-json` of all versions starting from `1.1.0` if use it in combination with `jackson-core` starting from version `2.10.0`.   

I've checked `io.protostuff.JsonIOUtil$Factory` and found, that this class [has method](https://github.com/protostuff/protostuff/blob/master/protostuff-json/src/main/java/io/protostuff/JsonIOUtil.java#L74) `getGeneratorFeatures()` and  extends jackson's class `com.fasterxml.jackson.core.JsonFactory`. In `jackson-core:2.10.0` in this class was added [new, final method](https://github.com/FasterXML/jackson-core/blob/2ce88904df6c60ef0c4708f6c514885cef850409/src/main/java/com/fasterxml/jackson/core/JsonFactory.java#L682) that has the same name as in `JsonIOUtil$Factory`.

Does it plan to make changes to support last version of jackson? Previous versions of jackson has vulnerabilities and I would like to avoid them by using the updated versions of jackson. Or, maybe, there are some workaround to avoid this issue?

**Comment by rymarm** [comment]
Oh, my wrong. It was already fixed in `1.7.0`: https://github.com/protostuff/protostuff/commit/11eb667d73fbbbfb6d4ea694d4922ff8d6542d45
