### ISSUE TITLE
Crash at benchmarks compilation 

### ISSUE THREAD

**Issue by thahgr** [protostuff/protostuff#320]
Compilation error at
Building protostuff :: benchmarks 1.4.4

the versions used are 
protostuff 1.4.4
annotation 1.1.0-rc01, We have also tried 1.3.0 which is latest

This appears on a mac machine which has been updated to java 11, from 1.8. It may be the case. Also Android studio and gradle have been updated. 

It used to run fine previously

We can provide any logs or anything more needed

Thank you

the errors and stack are below

[INFO] ------------------------------------------------------------------------
[INFO] Building protostuff :: benchmarks 1.4.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ protostuff-android-benchmarks ---
[INFO] Deleting MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ protostuff-android-benchmarks ---
[INFO] 
[INFO] --- protostuff-android-maven-plugin:1.4.4:compile (generate-sources) @ protostuff-android-benchmarks ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ protostuff-android-benchmarks ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ protostuff-android-benchmarks ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/A.java:[6,24] package javax.annotation does not exist
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/A.java:[20,2] cannot find symbol
  symbol: class Generated
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/GeneratedInt10.java:[6,24] package javax.annotation does not exist
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/GeneratedInt10.java:[20,2] cannot find symbol
  symbol: class Generated
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/GeneratedInt1.java:[6,24] package javax.annotation does not exist
[ERROR] MYPATHprotostuff_android/protostuff-android/protostuff-benchmarks/target/generated-sources/proto/io/protostuff/benchmarks/GeneratedInt1.java:[20,2] cannot find symbol
  symbol: class Generated
[ERROR] Annotation generator had thrown the exception. java.lang.NoClassDefFoundError: javax/annotation/Generated
  	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generateImport(BenchmarkGenerator.java:600)
  	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generateClass(BenchmarkGenerator.java:558)
  	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:119)
  	at org.openjdk.jmh.generators.BenchmarkProcessor.process(BenchmarkProcessor.java:58)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by dyu** [comment]
Can you try using `1.8.0-SNAPSHOT` and see if those errors persist?

**Comment by thahgr** [comment]
yes, this solved the problem, 
I just checked out latest commit since 1.8.0-SNAPSHOT doesnt exist in versions or tags, 

I guess you can close the ticket
