### ISSUE TITLE
how to deserialize protobuf map?

### ISSUE THREAD

**Issue by shakarelic** [protostuff/protostuff#322]

**Comment by shakarelic** [comment]
Caused by: io.protostuff.ProtostuffException: The map was incorrectly serialized.
	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:522)
	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:414)
	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:503)
	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:360)
	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:33)
	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:503)
	at io.protostuff.runtime.RuntimeMapFieldFactory$2.mergeFrom(RuntimeMapFieldFactory.java:186)
