### ISSUE TITLE
Issue while running on Java 17

### ISSUE THREAD

**Issue by LoreScianatico** [protostuff/protostuff#331]
While trying to generate a schema on Java 17 using protostuff-runtime API I got the following error:

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object java.util.Collections$SingletonSet.element accessible: module java.base does not "opens java.util" to unnamed module @2aceadd4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at io.protostuff.runtime.PolymorphicCollectionSchema.<clinit>(PolymorphicCollectionSchema.java:231)
	... 79 common frames omitted

Is this a known issue? Do I have to add some specific setting somewhere or do I have to write manually my schemas?

Thank you for your time.

**Comment by LoreScianatico** [comment]
After some tests, issue was not reproduced since not related to protostuff.
