### ISSUE TITLE
io.protostuff.runtime throws InaccessibleObjectException with jdk17

### ISSUE THREAD

**Issue by ik1220** [protostuff/protostuff#360]
io.protostuff: '1.6.2' was throwing InaccessibleObjectException so upgraded to 1.8.0 but the exception is still not resolved. Added "--add-opens=java.base/java.util=ALL_UNNAMED" to runtime docker image to get rid of this exception.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object java.util.Collections$SingletonMap.k accessible: module java.base does not "opens java.util" to unnamed module @49139829

```

Below is the full exception trace for your reference - 

```
Exception in thread "persistence-server-1" java.lang.ExceptionInInitializerError
	at io.protostuff.runtime.PolymorphicSchemaFactories$6.newSchema(PolymorphicSchemaFactories.java:164)
	at io.protostuff.runtime.RuntimeObjectField.<init>(RuntimeObjectField.java:41)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.<init>(RuntimeUnsafeFieldFactory.java:1224)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15.create(RuntimeUnsafeFieldFactory.java:1222)
	at io.protostuff.runtime.RuntimeMapFieldFactory$17.create(RuntimeMapFieldFactory.java:1718)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:275)
	at io.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:187)
	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:1625)
	at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:723)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:898)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:357)
	at io.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1244)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.DerivativeSchema.writeTo(DerivativeSchema.java:121)
	at io.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$14$1.writeTo(RuntimeUnsafeFieldFactory.java:1134)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.DerivativeSchema.writeTo(DerivativeSchema.java:121)
	at io.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at io.protostuff.runtime.RuntimeRepeatedFieldFactory$4.writeTo(RuntimeRepeatedFieldFactory.java:253)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:906)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:357)
	at io.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1244)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at io.protostuff.GraphIOUtil.writeTo(GraphIOUtil.java:319)
.......
	
	at io.grpc.MethodDescriptor.streamResponse(MethodDescriptor.java:319)
	at io.grpc.internal.ServerCallImpl.sendMessageInternal(ServerCallImpl.java:166)
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:149)
	at io.grpc.ForwardingServerCall.sendMessage(ForwardingServerCall.java:32)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:365)
......
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at 
.......
	at io.grpc.Context.run(Context.java:549)
	at
......
 io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	........
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	.......
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object java.util.Collections$SingletonMap.k accessible: module java.base does not "opens java.util" to unnamed module @49139829
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at io.protostuff.runtime.PolymorphicMapSchema.<clinit>(PolymorphicMapSchema.java:162) 
```

**Will there be another version of this library which works with jdk17 without requiring any "--add-opens" construct?**

**Comment by dyu** [comment]
```
Added "--add-opens=java.base/java.util=ALL_UNNAMED" to runtime docker image to get rid of this exception.
```
NIce workaround!
When I do upgrade beyond java8, I'll resolve the differences.  For now, PRs welcome
